// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxqbbuafllgmtzbqdete.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4cWJidWFmbGxnbXR6YnFkZXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODM2NjcsImV4cCI6MjA3MTI1OTY2N30.juPNh1hii3VO73zOFTsasFGRsSDgoOhhKAuX4mVP5PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});